### ISSUE TITLE
too many samples for BDSKY mode?

### ISSUE THREAD

**Issue by liamxg** [vjlab/omicronwave-hk#1]

**Comment by xieruopeng** [comment]
Thanks for your suggestion. We're doing sensitivity analysis using different sampling shcemes.

**Comment by xieruopeng** [comment]
No, only around 500 sequences after subsamping in the first version. Usually, to imporve computational efficiency, we'll contain less than 1000 sequences for Re estimation.

**Comment by xieruopeng** [comment]
To achieve ESS > 200

**Comment by xieruopeng** [comment]
kind of

**Comment by xieruopeng** [comment]
-resume parameter can help you, I think. In case the length.out you set is not enough, you can keep going.
