### ISSUE TITLE
why "Relative case detection rate" is >1?

### ISSUE THREAD

**Issue by liamxg** [vjlab/omicronwave-hk#4]
<img width="400" alt="image" src="https://github.com/vjlab/omicronwave-hk/assets/46078579/d0b3dc6c-08db-43c3-b303-18b6b26f393d">

**Comment by liamxg** [comment]
@xieruopeng

**Comment by xieruopeng** [comment]
Here, we just wanted to show the dynamics of the relative case detection rate. There is no meaning to the value.

**Comment by liamxg** [comment]
cool!
