### ISSUE TITLE
why "Incidence Rate (Covid cases/population)">1

### ISSUE THREAD

**Issue by liamxg** [vjlab/omicronwave-hk#5]
<img width="786" alt="image" src="https://github.com/vjlab/omicronwave-hk/assets/46078579/72ec85fc-386b-4ec0-ab95-c8d128877283">

**Comment by xieruopeng** [comment]
The y axis is covid cases per 100k population. Please refer to the latest version (https://www.nature.com/articles/s41467-023-38201-5)

**Comment by liamxg** [comment]
thanks.
