### ISSUE TITLE
how to generate the `Supplementary Data 1-Omicron_BA.1_MCC_summary` file?

### ISSUE THREAD

**Issue by liamxg** [vjlab/omicronwave-hk#8]
Dear @xieruopeng,

Could you please tell me how to  generate the `Supplementary Data 1-Omicron_BA.1_MCC_summary` file, thanks.

**Comment by xieruopeng** [comment]
https://github.com/sebastianduchene/summarise_importations

**Comment by liamxg** [comment]
Hi, @xieruopeng, thanks.

Could I know how to generate the `known_duration` and ` undetected_duration` columns as I do not find that in the above link?

Thanks in advance for your  help. 

Best,
Liam
